language: java
script: mvn integration-test -Dmaven.javadoc.skip=true --settings=.settings.xml -DredirectTestOutput=false
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V --settings=.settings.xml -DredirectTestOutput=false

dist: trusty

sudo: false

matrix:
  include:
  - jdk: openjdk8
  - jdk: openjdk9
  - jdk: openjdk10
  - jdk: openjdk11
  - jdk: openjdk-ea
  - jdk: oraclejdk8
  - jdk: oraclejdk11

      
cache:
  directories:
  - $HOME/.m2
